// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/hello.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Page                 uint32   `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_6c4e4c945aac522f, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Request) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_6c4e4c945aac522f, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SayClient is the client API for Say service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sayClient struct {
	cc *grpc.ClientConn
}

func NewSayClient(cc *grpc.ClientConn) SayClient {
	return &sayClient{cc}
}

func (c *sayClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Say/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayServer is the server API for Say service.
type SayServer interface {
	Hello(context.Context, *Request) (*Response, error)
}

func RegisterSayServer(s *grpc.Server, srv SayServer) {
	s.RegisterService(&_Say_serviceDesc, srv)
}

func _Say_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Say/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Say_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Say",
	HandlerType: (*SayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Say_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/hello.proto",
}

func init() { proto.RegisterFile("pb/hello.proto", fileDescriptor_hello_6c4e4c945aac522f) }

var fileDescriptor_hello_6c4e4c945aac522f = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8f, 0x41, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0x69, 0xfa, 0xaa, 0xbe, 0x51, 0x1f, 0x32, 0x88, 0x84, 0xc7, 0x43, 0x4a, 0x57, 0x5d,
	0x35, 0xa8, 0x37, 0x70, 0xa5, 0xdb, 0x78, 0x82, 0x94, 0x0e, 0x31, 0xd0, 0x26, 0xb1, 0x89, 0x82,
	0x88, 0x1b, 0xaf, 0xe0, 0xd1, 0xbc, 0x82, 0x07, 0x91, 0x24, 0xee, 0xbe, 0x7f, 0xf8, 0xff, 0x99,
	0xf9, 0x61, 0xe7, 0x47, 0xf1, 0x4c, 0xf3, 0xec, 0x06, 0xbf, 0xba, 0xe8, 0x90, 0xf9, 0x71, 0x7f,
	0xd0, 0xce, 0xe9, 0x99, 0x84, 0xf2, 0x46, 0x28, 0x6b, 0x5d, 0x54, 0xd1, 0x38, 0x1b, 0x8a, 0xa3,
	0x33, 0x70, 0x2c, 0xe9, 0xe5, 0x95, 0x42, 0xc4, 0x1d, 0x30, 0x33, 0xf1, 0xaa, 0xad, 0xfa, 0x73,
	0xc9, 0xcc, 0x84, 0x08, 0x1b, 0xab, 0x16, 0xe2, 0xac, 0xad, 0xfa, 0xad, 0xcc, 0x8c, 0x17, 0x50,
	0x2b, 0x4d, 0xbc, 0x6e, 0xab, 0xbe, 0x91, 0x09, 0x93, 0xcb, 0xa7, 0xd1, 0x26, 0xe7, 0x32, 0xe3,
	0x25, 0x34, 0xb3, 0x59, 0x4c, 0xe4, 0x4d, 0x5b, 0xf5, 0xb5, 0x2c, 0xa2, 0x3b, 0xc0, 0x89, 0xa4,
	0xe0, 0x9d, 0x0d, 0x79, 0xcf, 0x12, 0x74, 0x3e, 0xb6, 0x95, 0x09, 0x6f, 0x1f, 0xa1, 0x7e, 0x52,
	0xef, 0x78, 0x0f, 0xcd, 0x43, 0x2a, 0x80, 0xa7, 0x83, 0x1f, 0x87, 0xff, 0xd7, 0xf6, 0x67, 0x45,
	0x94, 0x70, 0x77, 0xfd, 0xf5, 0xf3, 0xfb, 0xcd, 0x38, 0x5e, 0x89, 0xb7, 0x1b, 0xa1, 0x57, 0xa2,
	0x48, 0x6b, 0xa9, 0x2d, 0x3e, 0xcc, 0xf4, 0x39, 0x1e, 0xe5, 0x6a, 0x77, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x91, 0xd8, 0x0f, 0x46, 0x0e, 0x01, 0x00, 0x00,
}
