// Code generated by protoc-gen-rest. DO NOT EDIT.
// source: pb/hello.proto

package pb

import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Server API for Say service
type sayServerClient struct {
	srv SayServer
}

func RegisterSayServerHandlerClient(ctx context.Context, mux *runtime.ServeMux, srv SayServer) error {
	return RegisterSayHandlerClient(ctx, mux, NewSayServerClient(srv))
}

func (h *sayServerClient) Hello(ctx context.Context, in *Request, _ ...grpc.CallOption) (*Response, error) {
	return h.srv.Hello(ctx, in)
}

func NewSayServerClient(srv SayServer) SayClient {
	return &sayServerClient{
		srv: srv,
	}
}
