// Code generated by protoc-gen-rest. DO NOT EDIT.
// source: main.proto

package pb


import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	runtime "github.com/grpc-ecosystem/grpc-gateway/runtime"
	grpc "google.golang.org/grpc"
	context "golang.org/x/net/context"
)


// Server API for Say service
type sayServerClient struct {
	srv SayServer
}

func RegisterSayServerHandlerClient(ctx context.Context, mux *runtime.ServeMux, srv SayServer) error {
	return RegisterSayHandlerClient(ctx, mux, NewSayServerClient(srv))
}

func (h *sayServerClient) Hello(ctx context.Context, in *Request, _ ...grpc.CallOption) (*Response, error) {
	return h.srv.Hello(ctx, in)
}

func (h *sayServerClient) Errors(ctx context.Context, in *empty.Empty, _ ...grpc.CallOption) (*empty.Empty, error) {
	return h.srv.Errors(ctx, in)
}

func (h *sayServerClient) Any(ctx context.Context, in *Data, _ ...grpc.CallOption) (*Data, error) {
	return h.srv.Any(ctx, in)
}

func NewSayServerClient(srv SayServer) SayClient {
	return &sayServerClient{
		srv: srv,
	}
}

