// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	Type_UNIVERSAL Type = 0
	Type_WEB       Type = 1
	Type_IMAGES    Type = 2
	Type_LOCAL     Type = 3
)

var Type_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
}
var Type_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_main_e698529d23d5d905, []int{0}
}

type Request_Type int32

const (
	Request_UNIVERSAL Request_Type = 0
	Request_WEB       Request_Type = 1
	Request_IMAGES    Request_Type = 2
	Request_LOCAL     Request_Type = 3
)

var Request_Type_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
}
var Request_Type_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}
func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_main_e698529d23d5d905, []int{0, 0}
}

type Request struct {
	Id                   uint32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32        `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Type                 Request_Type `protobuf:"varint,4,opt,name=type,proto3,enum=pb.Request_Type" json:"type,omitempty"`
	Page                 uint32       `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64        `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_main_e698529d23d5d905, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Request) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_UNIVERSAL
}

func (m *Request) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Type                 Type     `protobuf:"varint,2,opt,name=type,proto3,enum=pb.Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_main_e698529d23d5d905, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNIVERSAL
}

type Data struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_main_e698529d23d5d905, []int{2}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (dst *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(dst, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Data)(nil), "pb.Data")
	proto.RegisterEnum("pb.Type", Type_name, Type_value)
	proto.RegisterEnum("pb.Request_Type", Request_Type_name, Request_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SayClient is the client API for Say service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Errors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Any(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error)
}

type sayClient struct {
	cc *grpc.ClientConn
}

func NewSayClient(cc *grpc.ClientConn) SayClient {
	return &sayClient{cc}
}

func (c *sayClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Say/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayClient) Errors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.Say/Errors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayClient) Any(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/pb.Say/Any", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayServer is the server API for Say service.
type SayServer interface {
	Hello(context.Context, *Request) (*Response, error)
	Errors(context.Context, *empty.Empty) (*empty.Empty, error)
	Any(context.Context, *Data) (*Data, error)
}

func RegisterSayServer(s *grpc.Server, srv SayServer) {
	s.RegisterService(&_Say_serviceDesc, srv)
}

func _Say_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Say/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Say_Errors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServer).Errors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Say/Errors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServer).Errors(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Say_Any_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServer).Any(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Say/Any",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServer).Any(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

var _Say_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Say",
	HandlerType: (*SayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Say_Hello_Handler,
		},
		{
			MethodName: "Errors",
			Handler:    _Say_Errors_Handler,
		},
		{
			MethodName: "Any",
			Handler:    _Say_Any_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}

func init() { proto.RegisterFile("main.proto", fileDescriptor_main_e698529d23d5d905) }

var fileDescriptor_main_e698529d23d5d905 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x71, 0xfe, 0x6c, 0xbb, 0x43, 0x5b, 0xa2, 0x51, 0x55, 0x45, 0xa1, 0x42, 0x51, 0xc4,
	0x21, 0xea, 0x21, 0x11, 0x45, 0xbd, 0xf4, 0xb6, 0x85, 0x08, 0x2a, 0x2d, 0x20, 0x79, 0x0b, 0x9c,
	0xbd, 0x8a, 0x09, 0x96, 0x12, 0xdb, 0x24, 0x2e, 0x52, 0x84, 0xb8, 0xf0, 0x0a, 0xbc, 0x13, 0x2f,
	0x80, 0xc4, 0x13, 0xf0, 0x20, 0xc8, 0xce, 0x2e, 0xec, 0x85, 0x4b, 0x6f, 0xdf, 0x64, 0xf2, 0x7d,
	0xfe, 0xcd, 0x0c, 0x40, 0xc7, 0x84, 0x2c, 0x74, 0xaf, 0x8c, 0x42, 0x4f, 0xaf, 0x93, 0xd3, 0x46,
	0xa9, 0xa6, 0xe5, 0x25, 0xd3, 0xa2, 0x64, 0x52, 0x2a, 0xc3, 0x8c, 0x50, 0x72, 0x98, 0xfe, 0x48,
	0x1e, 0x6e, 0xba, 0xae, 0x5a, 0xdf, 0x7e, 0x28, 0x79, 0xa7, 0xcd, 0x38, 0x35, 0xb3, 0x1f, 0x04,
	0xf6, 0x28, 0xff, 0x74, 0xcb, 0x07, 0x83, 0x47, 0xe0, 0x89, 0x3a, 0x26, 0x29, 0xc9, 0x0f, 0xa9,
	0x27, 0x6a, 0x44, 0x08, 0x24, 0xeb, 0x78, 0xec, 0xa5, 0x24, 0x9f, 0x53, 0xa7, 0x31, 0x02, 0x9f,
	0x35, 0x3c, 0xf6, 0x53, 0x92, 0x87, 0xd4, 0x4a, 0x7c, 0x0c, 0x81, 0x19, 0x35, 0x8f, 0x83, 0x94,
	0xe4, 0x47, 0xe7, 0x51, 0xa1, 0xd7, 0xc5, 0x26, 0xb0, 0xb8, 0x19, 0x35, 0xa7, 0xae, 0x6b, 0xb3,
	0xb4, 0x35, 0x86, 0x2e, 0xdd, 0x69, 0x3c, 0x86, 0xb0, 0x15, 0x9d, 0x30, 0xf1, 0x2c, 0x25, 0xb9,
	0x4f, 0xa7, 0x22, 0xbb, 0x80, 0xc0, 0xfa, 0xf0, 0x10, 0xe6, 0x6f, 0x5f, 0x5f, 0xbf, 0xab, 0xe8,
	0x6a, 0xb1, 0x8c, 0xee, 0xe1, 0x1e, 0xf8, 0xef, 0xab, 0xab, 0x88, 0x20, 0xc0, 0xec, 0xfa, 0xd5,
	0xe2, 0x45, 0xb5, 0x8a, 0x3c, 0x9c, 0x43, 0xb8, 0x7c, 0xf3, 0x6c, 0xb1, 0x8c, 0xfc, 0xec, 0x12,
	0xf6, 0x29, 0x1f, 0xb4, 0x92, 0x83, 0x83, 0xec, 0x86, 0xc6, 0x4d, 0x32, 0xa7, 0x56, 0xe2, 0xe9,
	0x06, 0xd2, 0x73, 0x90, 0xfb, 0x16, 0xf2, 0x1f, 0x5c, 0x96, 0x40, 0xf0, 0x9c, 0x19, 0x66, 0x21,
	0x6b, 0x66, 0x98, 0x33, 0x1e, 0x50, 0xa7, 0xcf, 0xee, 0x86, 0x73, 0xfe, 0x8b, 0x80, 0xbf, 0x62,
	0x23, 0x5e, 0x41, 0xf8, 0x92, 0xb7, 0xad, 0xc2, 0xfb, 0x3b, 0x8b, 0x49, 0x0e, 0xa6, 0x62, 0xc2,
	0xcd, 0x1e, 0x7d, 0xfb, 0xf9, 0xfb, 0xbb, 0x17, 0xe3, 0x49, 0xf9, 0xf9, 0x49, 0xd9, 0xf4, 0x9c,
	0x1b, 0xde, 0x97, 0x1f, 0xad, 0xab, 0xfc, 0x22, 0xea, 0xaf, 0x78, 0x03, 0xb3, 0xaa, 0xef, 0x55,
	0x3f, 0xe0, 0x49, 0x31, 0xdd, 0xb2, 0xd8, 0xde, 0xb2, 0xa8, 0xec, 0x2d, 0x93, 0xff, 0x7c, 0xcf,
	0x12, 0x97, 0x7c, 0x8c, 0xb8, 0x9b, 0xcc, 0xa7, 0xac, 0x0b, 0xf0, 0x17, 0x72, 0x44, 0xb7, 0x0b,
	0x3b, 0x7d, 0xf2, 0x57, 0x6d, 0x6d, 0xd9, 0x83, 0x5d, 0x1b, 0x93, 0xe3, 0x25, 0x39, 0x5b, 0xcf,
	0xdc, 0x13, 0x4f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xf3, 0x25, 0x09, 0x84, 0x02, 0x00,
	0x00,
}
