// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: main.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Request) Validate() error {
	return nil
}
func (this *Response) Validate() error {
	return nil
}
func (this *Data) Validate() error {
	return nil
}
